# Module 1 scripts. Beat kinds: hero | broll | card | compare | checklist ; "price" overlay rides on a broll beat.
def L(title, typ, hook, beats, recap, summary, question, keywords, facts, quiz, introduces, uses=(), negative=False):
    return {"title": title, "type": typ, "hook": hook, "beats": beats, "recap": recap, "summary": summary,
            "question": question, "keywords": keywords, "facts": facts, "quiz": quiz,
            "introduces": list(introduces), "uses": list(uses), "negative": negative}
B = lambda text, q, **kw: dict({"kind": "broll", "text": text, "query": q}, **kw)
C = lambda title, text, q: {"kind": "card", "title": title, "text": text, "query": q}
V = lambda a, b, q: {"kind": "compare", "a": a, "b": b, "query": q}
K = lambda title, items, q: {"kind": "checklist", "title": title, "items": items, "query": q}
Q = lambda q, opts, a=0: {"q": q, "options": opts, "a": a}

M1 = [
L("Ի՞նչ է ֆինանսական շուկան", "concept", "Շուկան|միայն տոնավաճառ|չէ",
  [B("Շուկան այն տեղն է, որտեղ հանդիպում են գնորդներն ու վաճառողները", "farmers market stalls"),
   B("Ֆինանսական շուկայում առևտուր են անում բաժնետոմսերով, արժույթներով, ոսկով և crypto-ով", "city financial district"),
   C("Ֆինանսական շուկա", "Այնտեղ գնում և վաճառում են ֆինանսական ակտիվներ", "abstract blue light"),
   B("Այսօր դրա մեծ մասը կատարվում է առցանց՝ վայրկյանների ընթացքում", "city night timelapse")],
  "Շուկա՝|գնորդներ|և վաճառողներ",
  "Սկսում ենք զրոյից։ Առաջին դասը՝ ինչ է ֆինանսական շուկան և ինչու է այն ամեն ինչի հիմքը։",
  "Դու երբևէ մտածե՞լ ես, թե որտեղ է ձևավորվում Bitcoin-ի գինը։",
  ["ֆինանսական շուկա", "ինչ է շուկան", "financial market", "crypto դասընթաց"],
  ["Most trading in financial markets today happens electronically."],
  Q("Որտե՞ղ է այսօր կատարվում ֆինանսական գործարքների մեծ մասը", ["Առցանց", "Միայն բանկերում", "Տոնավաճառներում"]),
  ["market"]),
L("Ինչպե՞ս է ձևավորվում գինը", "concept", "Ո՞վ է որոշում|գինը",
  [B("Երբ գնորդները շատ են, իսկ վաճառողները՝ քիչ", "people shopping crowd"),
   B("գինը բարձրանում է", "city lights night", overlay={"type": "price", "from": 100, "to": 120, "dir": "up"}),
   B("Երբ վաճառողները շատ են, իսկ գնորդները՝ քիչ", "empty street morning"),
   B("գինը իջնում է", "rain window city", overlay={"type": "price", "from": 120, "to": 90, "dir": "down"}),
   C("Գին", "Այն կետը, որտեղ գնորդն ու վաճառողը համաձայնել են", "handshake close up")],
  "Գինը ձևավորում է|շուկան",
  "Առաջարկ և պահանջարկ. երկու ուժ, որոնք որոշում են ցանկացած ակտիվի գինը։",
  "Ո՞ր ապրանքի գինն է վերջերս քեզ զարմացրել։",
  ["ինչպես է ձևավորվում գինը", "առաջարկ և պահանջարկ", "supply and demand", "crypto դաս"],
  ["Price rises when demand exceeds supply and falls when supply exceeds demand."],
  Q("Ի՞նչ է լինում գնի հետ, երբ գնորդները շատ են, իսկ վաճառողները՝ քիչ", ["Բարձրանում է", "Իջնում է", "Չի փոխվում"]),
  ["price", "supply", "demand"], ["market"]),
L("Ի՞նչ է բորսան", "concept", "Ո՞վ է կապում|գնորդին|վաճառողի հետ",
  [B("Բորսան կազմակերպված շուկա է՝ հստակ կանոններով", "stock exchange building"),
   B("Այն համադրում է գնելու և վաճառելու հայտերը", "abstract network lights"),
   V(["Ֆոնդային բորսա", "Բաժնետոմսեր, օրինակ՝ NYSE"], ["Crypto բորսա", "Crypto, 24/7"], "abstract blue light"),
   B("Crypto բորսաները աշխատում են օրը 24 ժամ, շաբաթը 7 օր", "city night timelapse")],
  "Բորսա՝|կանոններով|շուկա",
  "Բորսան շուկայի կազմակերպված տարբերակն է։ Ինչպես է այն կապում գնորդներին և վաճառողներին։",
  "Իսկ դու գիտեի՞ր, որ crypto բորսաները երբեք չեն փակվում։",
  ["ինչ է բորսան", "crypto բորսա", "exchange", "stock exchange"],
  ["NYSE is a stock exchange.", "Crypto exchanges operate 24/7."],
  Q("Ե՞րբ են աշխատում crypto բորսաները", ["24/7", "Միայն աշխատանքային օրերին", "Միայն ցերեկը"]),
  ["exchange"], ["market", "price"]),
L("Trading և Investing", "concept", "Նույն Bitcoin-ը,|երկու տարբեր|մոտեցում",
  [B("Ներդրողը գնում է՝ տարիներով պահելու համար", "calm lake sunrise"),
   B("Թրեյդերը փորձում է շահել գնի կարճ շարժումներից", "fast traffic timelapse"),
   V(["Investing", "Տարիներ, քիչ գործարքներ"], ["Trading", "Րոպեներից օրեր, շատ գործարքներ"], "abstract blue light"),
   B("Թրեյդինգը պահանջում է գիտելիք, կարգապահություն և ժամանակ", "mountain climber")],
  "Ընտրիր|քո|ճանապարհը",
  "Ներդրումն ու թրեյդինգը տարբեր բաներ են։ Որն է տարբերությունը և ինչ է պահանջում յուրաքանչյուրը։",
  "Քեզ ավելի մոտ է ներդրո՞ւմը, թե՞ թրեյդինգը։",
  ["trading", "investing", "թրեյդինգ", "ներդրում", "crypto դաս հայերեն"],
  ["Investing is long-term holding; trading targets short-term price moves."],
  Q("Ո՞վ է սովորաբար պահում ակտիվը տարիներով", ["Ներդրողը", "Թրեյդերը", "Բորսան"]),
  ["trading", "investing"], ["price"]),
L("Ակտիվների դասեր", "concept", "Ինչո՞վ են|առևտուր անում|շուկաներում",
  [B("Ակտիվը այն է, ինչ արժեք ունի և կարող է գնվել ու վաճառվել", "gold bullion close up"),
   K("4 հիմնական դաս", ["Stocks՝ ընկերությունների մասեր", "Forex՝ արժույթներ", "Commodities՝ ոսկի, նավթ",
                         "Crypto՝ թվային ակտիվներ"], "abstract blue light"),
   B("Յուրաքանչյուր դաս ունի իր ռիսկը, իսկ crypto-ն ամենատատանվողներից է", "ocean waves storm")],
  "4 դաս՝|4 տարբեր|ռիսկ",
  "Stocks, Forex, Commodities և Crypto. ակտիվների 4 հիմնական դասերը և դրանց տարբերությունը։",
  "Այս 4-ից որի՞ն ես արդեն հանդիպել։",
  ["ակտիվ", "asset classes", "stocks forex crypto", "crypto դաս"],
  ["Stocks represent company ownership; forex is currencies; commodities include gold and oil."],
  Q("Ի՞նչ է Forex-ը", ["Արժույթների շուկա", "Ոսկու շուկա", "Crypto բորսա"]),
  ["asset", "stocks", "forex", "commodities", "crypto"], ["market"]),
L("Ի՞նչ է ինդեքսը", "concept", "Ինչպե՞ս չափել|ամբողջ|շուկան",
  [B("Ինդեքսը ցույց է տալիս մի խումբ ակտիվների ընդհանուր շարժումը", "city skyline day"),
   C("S&P 500", "ԱՄՆ-ի 500 խոշոր ընկերություններ մեկ թվում", "new york skyline"),
   B("Թրեյդերները հետևում են S&P 500-ին, որովհետև crypto-ն հաճախ արձագանքում է ընդհանուր տրամադրությանը",
     "city aerial night")],
  "Ինդեքս՝|շուկայի|ջերմաչափ",
  "Ինդեքսները ցույց են տալիս ամբողջ շուկայի ուղղությունը։ Ծանոթանանք S&P 500-ին։",
  "Դու հետևո՞ւմ ես S&P 500-ին։",
  ["S&P 500", "ինդեքս", "stock index", "crypto և ֆոնդային շուկա"],
  ["The S&P 500 tracks 500 large US companies."],
  Q("Քանի՞ ընկերություն է ներառում S&P 500-ը", ["500", "50", "5000"]),
  ["index"], ["stocks"]),
L("Ոսկին՝ ապահով նավահանգիստ", "concept", "Ինչո՞ւ են|ճգնաժամին|գնում ոսկի",
  [B("Ոսկին հազարավոր տարիներ համարվել է արժեքի պահպանման միջոց", "gold bullion close up"),
   C("XAU", "Ոսկու կոդը շուկայում. գինը՝ դոլարով մեկ ունցիայի համար", "gold texture close up"),
   B("Անորոշության ժամանակ շատերը գնում են ոսկի", "storm clouds"),
   B("դրա համար այն կոչվում է ապահով նավահանգիստ", "calm harbor boats")],
  "Ոսկի՝|ապահով|նավահանգիստ",
  "Ինչու է ոսկին կարևոր ամբողջ շուկայի համար և ինչ է նշանակում XAU-ն։",
  "Իսկ դու ոսկին համարո՞ւմ ես ապահով ակտիվ։",
  ["ոսկի", "XAU", "gold safe haven", "ոսկու գին"],
  ["Gold is quoted as XAU, priced in USD per troy ounce."],
  Q("Ինչպե՞ս է նշվում ոսկին շուկայում", ["XAU", "GLD", "OSK"]),
  ["gold"], ["commodities"]),
L("Ի՞նչ է Bitcoin-ը", "concept", "21 միլիոն.|ոչ մի|ավել",
  [B("Bitcoin-ը թվային արժույթ է՝ առանց կենտրոնական բանկի", "abstract digital network"),
   B("Այն գործում է 2009 թվականից", "night city lights"),
   C("Առավելագույն քանակ", "21 000 000 BTC", "abstract blue light"),
   B("Գործարքները ստուգում են աշխարհով մեկ սփռված համակարգիչներ", "server room lights")],
  "Bitcoin՝|սահմանափակ|թվային փող",
  "Bitcoin-ը առաջին և ամենահայտնի crypto-ն է։ Ինչ է այն և ինչու է նրա քանակը սահմանափակ։",
  "Ե՞րբ ես առաջին անգամ լսել Bitcoin-ի մասին։",
  ["ինչ է Bitcoin-ը", "Bitcoin explained", "Bitcoin հայերեն", "21 միլիոն"],
  ["Bitcoin launched in 2009.", "Bitcoin's maximum supply is 21 million."],
  Q("Որքա՞ն է Bitcoin-ի առավելագույն քանակը", ["21 միլիոն", "100 միլիոն", "Անսահմանափակ"]),
  ["bitcoin"], ["crypto"]),
L("Ի՞նչ է Blockchain-ը", "concept", "Մատյան,|որը հնարավոր չէ|կեղծել",
  [B("Blockchain-ը գործարքների մատյան է, որի պատճենը պահում են բազմաթիվ համակարգիչներ", "server room lights"),
   B("Գործարքները խմբավորվում են բլոկներում, և ամեն բլոկ կապված է նախորդին", "chain links close up"),
   C("Բլոկ → Բլոկ → Բլոկ", "Հին գրառումը փոխելը գրեթե անհնար է", "abstract blue light")],
  "Blockchain՝|ընդհանուր|մատյան",
  "Blockchain-ը crypto-ի հիմքն է։ Պարզ բացատրություն՝ ինչպես է այն աշխատում և ինչու է վստահելի։",
  "Կարո՞ղ ես մեկ նախադասությամբ բացատրել blockchain-ը ընկերոջդ։",
  ["ինչ է blockchain-ը", "blockchain explained", "բլոկչեյն", "crypto դաս"],
  ["Each block references the previous one, which makes past records very hard to alter."],
  Q("Ինչո՞վ է կապված յուրաքանչյուր բլոկը", ["Նախորդ բլոկով", "Բանկով", "Բորսայով"]),
  ["blockchain"], ["bitcoin"]),
L("Mining և Halving", "concept", "Ինչո՞ւ է|Bitcoin-ը|դանդաղում",
  [B("Մայներները ստուգում են գործարքները և պարգև ստանում նոր Bitcoin-ով", "computer hardware lights"),
   B("Halving-ի ժամանակ այդ պարգևը կրճատվում է կիսով չափ", "hourglass sand"),
   C("Halving", "Մոտ 4 տարին մեկ՝ յուրաքանչյուր 210 000 բլոկից հետո", "abstract blue light"),
   B("Նոր Bitcoin-ների թողարկումը ժամանակի հետ դանդաղում է", "slow river aerial")],
  "Mining + Halving|= սահմանափակ|թողարկում",
  "Ինչ են անում մայներները և ինչու է halving-ը Bitcoin-ի ամենաքննարկվող իրադարձություններից մեկը։",
  "Գիտեի՞ր, որ halving-ը տեղի է ունենում մոտ 4 տարին մեկ։",
  ["mining", "halving", "Bitcoin halving", "մայնինգ"],
  ["The Bitcoin block reward halves every 210,000 blocks, roughly every four years."],
  Q("Ի՞նչ է կատարվում halving-ի ժամանակ", ["Պարգևը կրճատվում է կիսով", "Գինը կրկնապատկվում է", "Bitcoin-ը փակվում է"]),
  ["mining", "halving"], ["bitcoin", "blockchain"]),
L("Bitcoin vs Altcoins", "concept", "Bitcoin-ից բացի|հազարավոր|coin-եր",
  [B("Altcoin են անվանում Bitcoin-ից բացի բոլոր crypto-ները", "abstract digital network"),
   V(["Bitcoin", "Առաջինը և ամենամեծը"], ["Altcoins", "Հազարավոր, տարբեր նպատակներով"], "abstract blue light"),
   B("Փոքր նախագծերը սովորաբար ավելի մեծ տատանումներ և ռիսկ ունեն", "rough sea waves")],
  "Ավելի փոքր|= ավելի|ռիսկային",
  "Ինչ են altcoin-ները և ինչու են դրանք սովորաբար ավելի ռիսկային, քան Bitcoin-ը։",
  "Ո՞ր altcoin-ն ես առաջինը լսել։",
  ["altcoin", "ինչ է altcoin-ը", "Bitcoin vs altcoins", "crypto դաս"],
  ["Altcoins are all cryptocurrencies other than Bitcoin."],
  Q("Ի՞նչ են altcoin-ները", ["Bitcoin-ից բացի բոլոր crypto-ները", "Bitcoin-ի տեսակ", "Բորսաներ"]),
  ["altcoin"], ["bitcoin"]),
L("Ethereum և Smart Contracts", "concept", "Blockchain,|որը գործարկում է|ծրագրեր",
  [B("Ethereum-ը blockchain է, որի վրա աշխատում են smart contract-ներ", "abstract blue light"),
   C("Smart contract", "Ծրագիր, որը ինքնաշխատ կատարում է պայմանները", "abstract network lights"),
   B("ETH-ը ցանցի արժույթն է, և դրանով վճարվում են միջնորդավճարները", "abstract digital network")],
  "Ethereum՝|ծրագրերի|հարթակ",
  "Ethereum-ը երկրորդ ամենամեծ crypto-ն է և բազմաթիվ ծառայությունների հիմքը։",
  "Իսկ դու գիտեի՞ր, որ blockchain-ի վրա կարելի է ծրագրեր գործարկել։",
  ["Ethereum", "smart contract", "ինչ է Ethereum-ը", "ETH"],
  ["ETH is used to pay transaction fees on the Ethereum network."],
  Q("Ի՞նչ է smart contract-ը", ["Ինքնաշխատ ծրագիր", "Բանկային պայմանագիր", "Wallet"]),
  ["ethereum", "smart_contract"], ["blockchain"]),
L("Stablecoins", "concept", "Crypto,|որը չի|տատանվում",
  [B("Stablecoin-ի գինը կապված է որևէ արժույթի, հաճախ՝ ԱՄՆ դոլարի", "abstract blue light"),
   C("USDT, USDC", "1 հատը նախատեսված է հավասար լինել 1 դոլարի", "abstract network lights"),
   B("Կայունությունը կախված է թողարկողից և նրա պահուստներից", "bank vault door")],
  "Stablecoin ≠|բանկային|ավանդ",
  "Stablecoin-ները կամուրջ են սովորական փողի և crypto-ի միջև։ Ինչպես են աշխատում և ինչ ռիսկ ունեն։",
  "Դու օգտագործե՞լ ես stablecoin։",
  ["stablecoin", "USDT", "USDC", "ինչ է stablecoin-ը"],
  ["USDT and USDC are designed to track 1 US dollar."],
  Q("Ինչի՞ց է կախված stablecoin-ի կայունությունը", ["Թողարկողից և պահուստներից", "Bitcoin-ի գնից", "Mining-ից"]),
  ["stablecoin"], ["crypto"]),
L("Market Cap", "concept", "Էժան coin-ը|էժան|չէ",
  [B("Market cap-ը նախագծի ընդհանուր շուկայական արժեքն է", "city skyline day"),
   C("Market Cap", "Գին × Շրջանառության քանակ", "abstract blue light"),
   B("Եթե 1 հատը 1 դոլար է, իսկ կա 1 միլիարդ հատ, market cap-ը 1 միլիարդ դոլար է", "abstract network lights")],
  "Նայիր ոչ թե գնին,|այլ|market cap-ին",
  "Market cap-ը օգնում է համեմատել նախագծերը։ Ինչու մեկ հատի գինը ամբողջ պատկերը չի տալիս։",
  "Որևէ անգամ գնե՞լ ես մի բան միայն այն պատճառով, որ այն «էժան» էր։",
  ["market cap", "շուկայական կապիտալիզացիա", "ինչ է market cap-ը", "crypto դաս"],
  ["Market cap = price × circulating supply."],
  Q("Ինչպե՞ս է հաշվարկվում market cap-ը", ["Գին × քանակ", "Գին + քանակ", "Միայն գինը"]),
  ["market_cap"], ["price"]),
L("Circulating և Total Supply", "concept", "Քանի՞ coin|կա իրականում",
  [B("Circulating supply-ը այն քանակն է, որն արդեն շրջանառության մեջ է", "people shopping crowd"),
   B("Total supply-ը ամբողջ քանակն է, ներառյալ դեռ արգելափակվածները", "bank vault door"),
   V(["Circulating", "Հիմա շուկայում"], ["Total", "Բոլորը միասին"], "abstract blue light"),
   B("Երբ արգելափակված coin-երը ազատվում են, առաջարկը մեծանում է", "dam water release")],
  "Ստուգիր|ոչ միայն գինը,|այլ supply-ը",
  "Circulating և total supply. ինչու է կարևոր իմանալ, թե որքան coin կա իրականում։",
  "Գնելուց առաջ ստուգո՞ւմ ես supply-ը։",
  ["circulating supply", "total supply", "tokenomics", "crypto դաս"],
  ["Token unlocks increase circulating supply."],
  Q("Ի՞նչ է լինում, երբ արգելափակված coin-երը ազատվում են", ["Առաջարկը մեծանում է", "Առաջարկը նվազում է", "Ոչինչ"]),
  ["circulating_supply", "total_supply"], ["market_cap", "supply"]),
L("Liquidity", "concept", "Կկարողանա՞ս|վաճառել,|երբ պետք լինի",
  [B("Liquidity-ն ցույց է տալիս, թե որքան հեշտ կարելի է գնել կամ վաճառել", "busy market crowd"),
   V(["Բարձր", "Bitcoin, խոշոր բաժնետոմսեր"], ["Ցածր", "Փոքր coin-եր"], "abstract blue light"),
   B("Ցածր liquidity-ի դեպքում մեծ գործարքը կարող է կտրուկ փոխել գինը", "narrow mountain road")],
  "Liquidity՝|վաճառելու|ազատություն",
  "Liquidity-ն որոշում է՝ կկարողանա՞ս վաճառել, երբ պետք լինի։",
  "Իսկ դու երբևէ չե՞ս կարողացել ինչ-որ բան արագ վաճառել։",
  ["liquidity", "լիկվիդություն", "ինչ է liquidity-ն", "crypto դաս"],
  ["Low-liquidity assets can move sharply on large orders."],
  Q("Ո՞րն ունի ավելի բարձր liquidity", ["Bitcoin-ը", "Նոր, փոքր coin-ը", "Երկուսը նույնը"]),
  ["liquidity"], ["market", "price"]),
L("Volatility", "concept", "10% մեկ օրում.|նորմա՞լ է",
  [B("Volatility-ն ցույց է տալիս, թե որքան ուժեղ և արագ է փոխվում գինը", "ocean waves"),
   B("Crypto-ում 10% շարժումը մեկ օրում հազվադեպ չէ", "roller coaster"),
   C("Կանոն", "Ներդրիր այնքան, որ տատանումները քեզ քնից չզրկեն", "calm lake sunrise")],
  "Բարձր volatility|= բարձր|ռիսկ",
  "Crypto-ն հայտնի է ուժեղ տատանումներով։ Ինչ է volatility-ն և ինչպես վարվել դրա հետ։",
  "Քո կարծիքով որքա՞ն տատանումն է «նորմալ»։",
  ["volatility", "տատանողականություն", "crypto volatility", "crypto դաս"],
  ["Crypto assets can move 10% or more in a single day."],
  Q("Ի՞նչ է ցույց տալիս volatility-ն", ["Գնի փոփոխության ուժը և արագությունը", "Market cap-ը", "Supply-ը"]),
  ["volatility"], ["price", "crypto"]),
L("Bull Market և Bear Market", "concept", "Ցուլ|թե|արջ",
  [B("Bull շուկան երկարատև աճի ժամանակաշրջան է", "bull field"),
   B("Bear շուկան երկարատև անկման ժամանակաշրջան է", "brown bear forest"),
   V(["Bull", "Ցուլը հարվածում է ներքևից վերև"], ["Bear", "Արջը՝ վերևից ներքև"], "abstract blue light"),
   B("Բաժնետոմսերում 20% անկումը հաճախ համարվում է bear շուկայի նշան", "storm clouds")],
  "Bull՝ աճ,|Bear՝|անկում",
  "Bull և Bear. թրեյդերների ամենահաճախ օգտագործվող երկու բառը և դրանց ծագումը։",
  "Հիմա, քո կարծիքով, crypto-ն bull, թե՞ bear շուկայում է։",
  ["bull market", "bear market", "բուլ և բեր շուկա", "crypto դաս"],
  ["A 20% decline in stocks is commonly used as a bear market threshold."],
  Q("Ի՞նչ է bull շուկան", ["Երկարատև աճ", "Երկարատև անկում", "Կայուն գին"]),
  ["bull", "bear"], ["market"]),
L("FOMO և FUD", "concept", "Բոլորը գնում են.|իսկ դու՞",
  [B("FOMO-ն բաց թողնելու վախն է, երբ գնում ես միայն այն պատճառով, որ բոլորը գնում են", "crowd city street"),
   B("FUD-ը վախ, անորոշություն և կասկած տարածող խոսակցություններն են", "dark storm clouds"),
   C("Կանոն", "Որոշումից առաջ ստուգիր աղբյուրը և փաստերը", "calm lake sunrise")],
  "Հույզերը|վատ|խորհրդատուներ են",
  "FOMO և FUD. երկու հույզ, որոնք բացատրում են crypto շուկայի շատ սխալներ։",
  "Երբևէ գնե՞լ ես ինչ-որ բան FOMO-ի պատճառով։",
  ["FOMO", "FUD", "crypto հոգեբանություն", "crypto դաս"],
  ["FUD stands for fear, uncertainty and doubt."],
  Q("Ի՞նչ է FOMO-ն", ["Բաց թողնելու վախը", "Crypto բորսա", "Ինդեքս"]),
  ["fomo", "fud"], ["market"]),
L("Ռիսկ և շահույթ", "concept", "Ինչո՞ւ բարձր շահույթը|միշտ ունի|գին",
  [B("Որքան մեծ է հնարավոր շահույթը, այնքան մեծ է սովորաբար ռիսկը", "mountain climber"),
   V(["Ավանդ", "Փոքր, բայց կայուն"], ["Crypto", "Հնարավոր մեծ աճ և մեծ անկում"], "abstract blue light"),
   C("Առաջին կանոն", "Մի՛ ներդրիր այն, ինչի կորուստը չես կարող թույլ տալ", "calm lake sunrise")],
  "Ռիսկը|միշտ|առաջինն է",
  "Ֆինանսների ամենակարևոր կանոնը՝ ռիսկի և շահույթի կապը։",
  "Որքա՞ն ռիսկ ես պատրաստ ընդունել։",
  ["ռիսկ և շահույթ", "risk reward", "crypto ռիսկ", "crypto դաս"],
  ["Higher potential returns generally come with higher risk."],
  Q("Ո՞րն է առաջին կանոնը", ["Չներդնել այն, ինչի կորուստը չես կարող թույլ տալ", "Միշտ գնել էժանը", "Հետևել բոլորին"]),
  ["risk"], ["crypto"]),
L("DeFi-ի գաղափարը", "concept", "Ֆինանսներ|առանց|բանկի",
  [B("DeFi-ն ֆինանսական ծառայություններ են, որոնք աշխատում են blockchain-ի ծրագրերով", "abstract network lights"),
   K("Ինչ կարելի է անել", ["Փոխանակել crypto", "Տալ և վերցնել վարկ", "Վաստակել տոկոս"], "abstract blue light"),
   B("Ծրագրային սխալը կամ hack-ը կարող է հանգեցնել գումարի կորստի", "dark storm clouds")],
  "Բարձր տոկոս|= բարձր|ռիսկ",
  "DeFi-ն փորձում է ֆինանսական ծառայությունները տեղափոխել blockchain։ Հնարավորություններն ու ռիսկերը՝ պարզ։",
  "Դու վստահո՞ւմ ես ֆինանսներին առանց բանկի։",
  ["DeFi", "decentralized finance", "ինչ է DeFi-ն", "crypto դաս"],
  ["DeFi runs on smart contracts; bugs or hacks can cause losses."],
  Q("Ի՞նչն է DeFi-ի հիմնական ռիսկը", ["Ծրագրային սխալ կամ hack", "Բանկի փակվելը", "Halving-ը"]),
  ["defi"], ["blockchain", "smart_contract", "risk"]),
L("Ամփոփում + տնային առաջադրանք", "explain", "Ամբողջ պատկերը|մեկ|րոպեում",
  [B("Շուկայում գնորդներն ու վաճառողները ձևավորում են գինը", "busy market crowd"),
   B("Բորսան կապում է նրանց կանոններով", "stock exchange building"),
   B("Ակտիվները տարբեր են՝ բաժնետոմսերից մինչև Bitcoin", "gold bullion close up"),
   B("Յուրաքանչյուրն ունի իր liquidity-ն և volatility-ն", "ocean waves"),
   C("Տնային առաջադրանք", "Գտիր Bitcoin-ի և Ethereum-ի market cap-ը և համեմատիր", "abstract blue light")],
  "Մոդուլ 1|ավարտված է",
  "Մոդուլ 1-ի ամփոփում և առաջին տնային առաջադրանքը։ Հաջորդը՝ անվտանգություն և բորսա։",
  "Ո՞ր դասն էր քեզ համար ամենաօգտակարը այս մոդուլում։",
  ["crypto դասընթաց", "crypto սկսնակների համար", "crypto հայերեն", "trading դաս"],
  [],
  Q("Ո՞վ է ձևավորում գինը շուկայում", ["Գնորդներն ու վաճառողները", "Բորսան", "Կառավարությունը"]),
  [], ["market", "price", "exchange", "liquidity", "volatility", "market_cap"]),
]
