# Module 2: security, scams and the exchange. Negative (scam) lessons never use footage with faces.
from m1 import L, B, C, V, K, Q

M2 = {
1: L("Wallet-ի տեսակները", "concept", "Որտե՞ղ են|իրականում պահվում|քո coin-երը",
  [B("Crypto wallet-ը պահում է բանալիները, որոնցով կառավարում ես քո coin-երը", "smartphone app closeup"),
   V(["Hot wallet", "Միացված է ինտերնետին, հարմար է"], ["Cold wallet", "Անջատված է, ավելի անվտանգ"], "technology blue"),
   B("Բորսայում պահելիս բանալիները բորսայի մոտ են, ոչ թե քո", "bank vault door")],
  "Ով ունի բանալին,|նա է տերը",
  "Hot, cold և բորսայի wallet. որտեղ են պահվում coin-երը և ինչով են տարբերվում։",
  "Դու որտե՞ղ ես պահում քո crypto-ն։",
  ["crypto wallet", "hot wallet", "cold wallet", "wallet հայերեն"],
  ["Hot wallets are online; cold wallets are kept offline."],
  Q("Ո՞ր wallet-ն է անջատված ինտերնետից", ["Cold wallet", "Hot wallet", "Բորսայի wallet"]),
  ["wallet"], ["crypto", "exchange"]),
2: L("Private Key և Seed Phrase", "concept", "12 բառ,|որոնք արժեն|ամեն ինչ",
  [B("Private key-ը գաղտնի բանալի է, որով հաստատվում են գործարքները", "padlock closeup"),
   B("Seed phrase-ը 12 կամ 24 բառ է, որով կարելի է վերականգնել ամբողջ wallet-ը", "notebook handwriting pen"),
   C("Կանոն", "Seed phrase-ը երբեք մի՛ ուղարկիր ոչ մեկին, նույնիսկ «support»-ին", "dark room laptop")],
  "Seed phrase՝|միայն քեզ",
  "Private key և seed phrase. ամենակարևոր գաղտնիքները crypto-ում և ինչպես պաշտպանել դրանք։",
  "Գիտեի՞ր, որ seed phrase-ով մեկը կարող է վերցնել ամբողջ wallet-ը։",
  ["seed phrase", "private key", "crypto անվտանգություն", "wallet վերականգնում"],
  ["A seed phrase is usually 12 or 24 words and can restore a wallet."],
  Q("Ո՞ւմ կարելի է ասել seed phrase-ը", ["Ոչ մեկին", "Բորսայի support-ին", "Ընկերոջը"]),
  ["private_key", "seed_phrase"], ["wallet"]),
3: L("Անվտանգության հիմունքներ", "concept", "Hacker-ին|պետք չէ քո|համակարգիչը",
  [B("Մեծ մասամբ գումարը կորչում է ոչ թե hack-ից, այլ մարդկային սխալից", "laptop password screen"),
   K("Հիմնական կանոններ", ["Ամեն տեղ՝ տարբեր գաղտնաբառ", "Միացրու 2FA", "Մի՛ սեղմիր անծանոթ հղումներ"], "technology blue"),
   B("Եթե առաջարկը չափազանց լավ է թվում, հավանաբար խաբեություն է", "dark storm clouds")],
  "Զգուշությունը|լավագույն|պաշտպանությունն է",
  "Crypto անվտանգության հիմնական կանոնները, որոնք պաշտպանում են գումարի մեծ մասը։",
  "Դու օգտագործո՞ւմ ես տարբեր գաղտնաբառեր տարբեր կայքերի համար։",
  ["crypto անվտանգություն", "crypto security", "գաղտնաբառ", "crypto դաս"],
  ["Many crypto losses come from phishing and human error rather than protocol hacks."],
  Q("Ինչո՞վ է մեծ մասամբ կորչում գումարը", ["Մարդկային սխալով", "Bitcoin-ի սխալով", "Halving-ով"]),
  ["security"], ["seed_phrase"]),
4: L("2FA", "concept", "Գաղտնաբառը|բավական|չէ",
  [B("2FA-ն երկրորդ պաշտպանության քայլ է գաղտնաբառից հետո", "smartphone security lock"),
   V(["SMS կոդ", "Ավելի թույլ"], ["Authenticator հավելված", "Ավելի ուժեղ"], "technology blue"),
   C("Կանոն", "Պահիր 2FA-ի վերականգնման կոդերը անվտանգ տեղում", "notebook handwriting pen")],
  "2FA՝|երկրորդ|դուռ",
  "2FA-ն պաշտպանում է նույնիսկ այն դեպքում, եթե գաղտնաբառը գողացել են։",
  "Քո բորսայի հաշվում 2FA-ն միացվա՞ծ է։",
  ["2FA", "երկքայլ նույնականացում", "authenticator", "crypto անվտանգություն"],
  ["Authenticator apps are generally safer than SMS codes because of SIM-swap attacks."],
  Q("Ո՞ր 2FA-ն է ավելի ուժեղ", ["Authenticator հավելվածը", "SMS կոդը", "Երկուսն էլ նույնն են"]),
  ["2fa"], ["security"]),
5: L("Ինչպես ստուգել կայքը", "concept", "Մեկ տառ|և գումարը|չկա",
  [B("Խաբեբաները ստեղծում են կայքեր, որոնք գրեթե չեն տարբերվում իսկականից", "laptop screen dark"),
   K("Ստուգիր", ["Հասցեն՝ տառ առ տառ", "Մուտքը՝ միայն էջանիշից", "Գովազդային հղումները՝ ոչ"], "technology blue"),
   B("Հավելվածները ներբեռնիր միայն պաշտոնական խանութից", "smartphone app closeup")],
  "Ստուգիր|հասցեն|ամեն անգամ",
  "Կեղծ կայքերը crypto-ում ամենատարածված ծուղակներից են։ Ինչպես տարբերել իսկականը։",
  "Դու երբևէ հանդիպե՞լ ես կեղծ կայքի։",
  ["phishing", "կեղծ կայք", "crypto scam", "crypto անվտանգություն"],
  ["Phishing sites often copy real domains with one changed character."],
  Q("Ինչպե՞ս է ավելի անվտանգ մուտք գործել բորսա", ["Էջանիշից", "Գովազդի հղումից", "Անծանոթ նամակից"]),
  ["phishing"], ["security"]),
6: L("Scam. կեղծ support", "concept", "«Support»-ը|քեզ առաջինը|չի գրում",
  [B("Խաբեբան ներկայանում է որպես բորսայի կամ wallet-ի support", "smartphone notification night"),
   B("Նա խնդրում է seed phrase-ը կամ կոդը՝ «հաշիվը փրկելու համար»", "dark room laptop"),
   C("Կանոն", "Իսկական support-ը երբեք չի խնդրում seed phrase կամ 2FA կոդ", "padlock closeup")],
  "Seed phrase խնդրող|support-ը|խաբեբա է",
  "Մի՛ խաբվիր. կեղծ support-ը crypto-ում ամենահաճախ հանդիպող խաբեություններից է։",
  "Քեզ երբևէ գրե՞լ է «support»՝ առանց քո դիմելու։",
  ["crypto scam", "կեղծ support", "խաբեություն", "մի խաբվիր"],
  ["Legitimate support never asks for seed phrases or 2FA codes."],
  Q("Ի՞նչ է անում իսկական support-ը", ["Երբեք չի խնդրում seed phrase", "Խնդրում է 2FA կոդ", "Գրում է առաջինը"]),
  ["scam"], ["seed_phrase", "2fa"], negative=True),
7: L("Scam. բուրգեր", "concept", "Կայուն 30%|ամեն|ամիս",
  [B("Բուրգը խոստանում է կայուն, բարձր եկամուտ առանց ռիսկի", "money stack closeup"),
   B("Հին մասնակիցներին վճարում են նորերի գումարով, մինչև համակարգը փլուզվում է", "dominoes falling"),
   C("Նշան", "Երաշխավորված բարձր տոկոս և «բեր ընկերոջդ» պահանջ", "dark storm clouds")],
  "Երաշխավորված տոկոս|= կարմիր|դրոշ",
  "Մի՛ խաբվիր. ինչպես ճանաչել ֆինանսական բուրգը նախքան գումար ներդնելը։",
  "Քեզ երբևէ առաջարկե՞լ են «կայուն եկամուտ» crypto-ով։",
  ["ֆինանսական բուրգ", "Ponzi", "crypto scam", "մի խաբվիր"],
  ["Ponzi schemes pay earlier investors with money from new investors."],
  Q("Ինչո՞վ են բուրգերը վճարում հին մասնակիցներին", ["Նորերի գումարով", "Շահույթով", "Bitcoin-ի mining-ով"]),
  [], ["scam"], negative=True),
8: L("Scam. կեղծ giveaway", "concept", "Ուղարկիր 1,|ստացիր|2",
  [B("Կեղծ giveaway-ը խոստանում է կրկնապատկել քո ուղարկած crypto-ն", "smartphone notification night"),
   B("Հաճախ օգտագործում են հայտնի մարդկանց անունները և կեղծ վիդեոներ", "dark room laptop"),
   C("Կանոն", "Ոչ ոք չի կրկնապատկում քո գումարը. ուղարկածը չի վերադառնա", "padlock closeup")],
  "Անվճար crypto|չի|լինում",
  "Մի՛ խաբվիր. «ուղարկիր և կրկնապատկիր» giveaway-ները միշտ խաբեություն են։",
  "Դու տեսե՞լ ես նման giveaway սոցցանցերում։",
  ["crypto giveaway", "crypto scam", "կեղծ giveaway", "մի խաբվիր"],
  ["Crypto 'send to double' giveaways are scams."],
  Q("Ի՞նչ է լինում ուղարկված գումարի հետ", ["Չի վերադառնում", "Կրկնապատկվում է", "Վերադառնում է մեկ օրից"]),
  [], ["scam"], negative=True),
9: L("Scam. ծանոթությունից ներդրում", "concept", "Նոր ընկեր,|որը խոսում է|միայն crypto-ից",
  [B("Խաբեբան ամիսներով կառուցում է վստահություն ծանոթության կայքերում կամ սոցցանցերում", "smartphone chat night"),
   B("Հետո առաջարկում է «իր» հարթակը, որտեղ շահույթը միայն էկրանին է", "laptop screen dark"),
   C("Կանոն", "Մի՛ ներդրիր այնտեղ, որտեղ քեզ ուղղորդում է անծանոթը", "dark storm clouds")],
  "Վստահությունը|չի նշանակում|անվտանգություն",
  "Մի՛ խաբվիր. երկար շփումից հետո crypto ներդրման առաջարկը դասական խաբեություն է։",
  "Կզգուշացնե՞ս ընկերոջդ, եթե նա պատմի նման «նոր ընկերոջ» մասին։",
  ["romance scam", "crypto scam", "pig butchering", "մի խաբվիր"],
  ["These scams build trust over weeks before pushing a fake investment platform."],
  Q("Որտե՞ղ է «շահույթը» նման հարթակներում", ["Միայն էկրանին", "Բանկում", "Blockchain-ում"]),
  [], ["scam"], negative=True),
10: L("Scam. pump and dump", "concept", "Գինը թռավ.|հետո|փլուզվեց",
  [B("Կազմակերպիչները գնում են էժան coin, ապա գովազդում այն", "crowd city street"),
   B("Երբ նորեկները գնում են, նրանք վաճառում են և գինը փլուզվում է", "stock chart falling red"),
   C("Նշան", "Կտրուկ աճ առանց պատճառի և «շտապիր գնել» կոչեր", "dark storm clouds")],
  "Շտապեցնողը|սովորաբար|վաճառում է",
  "Մի՛ խաբվիր. ինչպես է աշխատում pump and dump-ը և ով է իրականում շահում։",
  "Գնե՞լ ես երբևէ coin, որի մասին «բոլորը խոսում էին»։",
  ["pump and dump", "crypto scam", "manipulation", "մի խաբվիր"],
  ["Pump-and-dump schemes inflate a price then sell to latecomers."],
  Q("Ո՞վ է շահում pump and dump-ից", ["Կազմակերպիչները", "Ուշացած գնորդները", "Բոլորը"]),
  [], ["scam", "price"], negative=True),
11: L("Scam. կեղծ airdrop", "concept", "Անվճար token-ը|քո wallet-ում|հենց այնպես",
  [B("Wallet-ում հայտնվում է անծանոթ token՝ հղումով դեպի կայք", "smartphone app closeup"),
   B("Այդ կայքը խնդրում է «հաստատել» գործարք, որը դատարկում է wallet-ը", "laptop screen dark"),
   C("Կանոն", "Անծանոթ token-ների հետ ոչինչ մի՛ արա և մի՛ սեղմիր հղումները", "padlock closeup")],
  "Անծանոթ token՝|մի՛|դիպչիր",
  "Մի՛ խաբվիր. կեղծ airdrop-ները և wallet drainer-ները կարող են դատարկել wallet-ը մեկ սեղմումով։",
  "Քո wallet-ում երբևէ հայտնվե՞լ է անծանոթ token։",
  ["airdrop scam", "wallet drainer", "crypto scam", "մի խաբվիր"],
  ["Wallet drainers trick users into signing malicious approvals."],
  Q("Ի՞նչ անել անծանոթ token-ի հետ", ["Ոչինչ չանել", "Վաճառել անմիջապես", "Սեղմել հղումը"]),
  [], ["scam", "wallet"], negative=True),
12: L("Scam. «VIP ազդանշաններ»", "concept", "100% ճշգրիտ|ազդանշաններ.|միայն վճարով",
  [B("Խմբերը վաճառում են «գաղտնի ազդանշաններ» և ցույց տալիս միայն հաջող գործարքները", "smartphone chat night"),
   B("Կորուստները ջնջվում են, իսկ արդյունքները հաճախ կեղծ են", "laptop screen dark"),
   C("Կանոն", "Ոչ ոք չի կարող երաշխավորել շահույթ շուկայում", "calm lake sunrise")],
  "Երաշխիք|չկա|շուկայում",
  "Մի՛ խաբվիր. «VIP ազդանշանների» խմբերը սովորաբար վաստակում են քո վճարից, ոչ թե շուկայից։",
  "Քեզ երբևէ առաջարկե՞լ են վճարովի ազդանշաններ։",
  ["crypto signals", "VIP signals", "crypto scam", "մի խաբվիր"],
  ["No one can guarantee trading profits."],
  Q("Ինչո՞վ են հաճախ վաստակում «VIP» խմբերը", ["Բաժանորդների վճարով", "Միայն շուկայից", "Mining-ով"]),
  [], ["scam", "trading"], negative=True),
13: L("Բորսայի կառուցվածքը", "concept", "Ի՞նչ է կատարվում|«Գնել» սեղմելուց|հետո",
  [B("Crypto բորսան միացնում է գնորդների և վաճառողների հայտերը", "technology network connection"),
   V(["CEX", "Կենտրոնացված, ընկերություն"], ["DEX", "Smart contract-ներով"], "technology blue"),
   B("Կենտրոնացված բորսայում քո գումարը պահվում է բորսայի մոտ", "bank vault door")],
  "Բորսա՝|միջնորդ|կանոններով",
  "Ինչպես է աշխատում crypto բորսան և ինչ տարբերություն կա CEX-ի և DEX-ի միջև։",
  "Դու օգտագործե՞լ ես երբևէ DEX։",
  ["crypto բորսա", "CEX", "DEX", "exchange"],
  ["Centralized exchanges hold user funds; DEXs use smart contracts."],
  Q("Ինչո՞վ է աշխատում DEX-ը", ["Smart contract-ներով", "Բանկով", "Թղթային գործարքներով"]),
  ["cex", "dex"], ["exchange", "smart_contract"]),
14: L("Ինչպես ընտրել բորսա", "concept", "Ամենամեծ բոնուսը|ամենավատ|չափանիշն է",
  [B("Բորսա ընտրելիս կարևոր է ոչ թե գովազդը, այլ վստահելիությունը", "city financial district"),
   K("Ստուգիր", ["Լիցենզիա և կարգավորում", "Անվտանգության պատմություն", "Լիկվիդություն և միջնորդավճարներ"], "technology blue"),
   B("Մեծ գումար երկար ժամանակ բորսայում մի՛ պահիր", "bank vault door")],
  "Վստահություն|> բոնուս",
  "Բորսա ընտրելու չափանիշները. ինչին նայել և ինչից զգուշանալ։",
  "Ո՞ր չափանիշն է քեզ համար ամենակարևորը։",
  ["ինչպես ընտրել բորսա", "crypto exchange", "կարգավորվող բորսա", "crypto դաս"],
  ["Regulation and security history matter more than bonuses."],
  Q("Ո՞րն է ամենաթույլ չափանիշը", ["Ամենամեծ բոնուսը", "Լիցենզիան", "Անվտանգությունը"]),
  [], ["exchange", "liquidity"]),
15: L("Trading Pair", "concept", "BTC/USDT.|ի՞նչ է նշանակում|շեղը",
  [B("Trading pair-ը ցույց է տալիս, թե որ ակտիվն ես փոխանակում որի հետ", "technology blue"),
   C("BTC/USDT", "Գնում ես BTC՝ վճարելով USDT-ով", "digital network technology"),
   B("Առաջին ակտիվը գնվում կամ վաճառվում է, երկրորդով չափվում է գինը", "city skyline day")],
  "Զույգ՝|ինչ ես գնում|և ինչով",
  "Trading pair-ը բորսայի հիմնական հասկացություններից է։ Ինչպես կարդալ BTC/USDT-ն։",
  "Ո՞ր զույգով ես առավել հաճախ հանդիպում։",
  ["trading pair", "BTC/USDT", "զույգ", "crypto դաս"],
  ["In BTC/USDT, BTC is the base asset and USDT is the quote asset."],
  Q("BTC/USDT-ում ինչո՞վ ես վճարում", ["USDT-ով", "BTC-ով", "Դոլարով բանկից"]),
  ["trading_pair"], ["exchange", "stablecoin"]),
16: L("USDT և quote currency", "concept", "Ինչո՞ւ են|գները|USDT-ով",
  [B("Quote currency-ն այն արժույթն է, որով չափվում է գինը", "technology blue"),
   B("Շատ բորսաներում դա USDT-ն կամ USDC-ն է, որոնք կապված են դոլարին", "money stack closeup"),
   C("Հիշիր", "Stablecoin-ի արժեքը կախված է թողարկողից", "bank vault door")],
  "Quote currency՝|գնի|չափանիշ",
  "Ինչու են crypto գները մեծ մասամբ USDT-ով և ինչ է quote currency-ն։",
  "Դու օգտագործո՞ւմ ես USDT։",
  ["USDT", "quote currency", "stablecoin", "crypto դաս"],
  ["Many crypto pairs are quoted in USDT or USDC."],
  Q("Ի՞նչ է quote currency-ն", ["Արժույթը, որով չափվում է գինը", "Գնվող ակտիվը", "Միջնորդավճարը"]),
  ["quote_currency"], ["trading_pair", "stablecoin"]),
17: L("Ի՞նչ է պոզիցիան", "concept", "Գնեցիր.|հիմա դու|պոզիցիայում ես",
  [B("Պոզիցիան քո բաց գործարքն է, որի արդյունքը կախված է գնից", "city lights night"),
   V(["Բաց պոզիցիա", "Արդյունքը դեռ փոխվում է"], ["Փակ պոզիցիա", "Արդյունքը ֆիքսված է"], "technology blue"),
   B("Ամեն պոզիցիայի համար պետք է պլան՝ որտեղ դուրս գալ", "chess board closeup")],
  "Պոզիցիա՝|պլանով",
  "Պոզիցիան թրեյդինգի հիմնական հասկացությունն է։ Ինչ է բաց և փակ պոզիցիան։",
  "Դու նախօրոք որոշո՞ւմ ես, թե որտեղ դուրս գալ գործարքից։",
  ["պոզիցիա", "position", "թրեյդինգ", "crypto դաս"],
  ["An open position's result changes with price until it is closed."],
  Q("Ե՞րբ է արդյունքը ֆիքսվում", ["Պոզիցիան փակելիս", "Բացելիս", "Երբեք"]),
  ["position"], ["trading", "price"]),
18: L("Bid, Ask և Spread", "concept", "Ինչո՞ւ են|երկու|գին",
  [B("Bid-ը ամենաբարձր գինն է, որով պատրաստ են գնել", "people shopping crowd"),
   B("Ask-ը ամենացածր գինն է, որով պատրաստ են վաճառել", "farmers market stalls"),
   C("Spread", "Ask-ի և Bid-ի տարբերությունը", "technology blue")],
  "Փոքր spread|= բարձր|լիկվիդություն",
  "Bid, ask և spread. ինչու շուկայում միշտ երկու գին կա։",
  "Նկատե՞լ ես, որ գնման և վաճառքի գները տարբեր են։",
  ["bid ask", "spread", "order book", "crypto դաս"],
  ["The spread is the difference between the best ask and best bid."],
  Q("Ի՞նչ է spread-ը", ["Ask-ի և Bid-ի տարբերությունը", "Միջնորդավճարը", "Գնի աճը"]),
  ["bid", "ask", "spread"], ["price", "liquidity"]),
19: L("Market Order", "concept", "Գնել|հենց|հիմա",
  [B("Market order-ը կատարվում է անմիջապես՝ առկա լավագույն գնով", "fast traffic timelapse"),
   B("Արագ է, բայց վերջնական գինը կարող է մի փոքր տարբերվել", "city lights night"),
   C("Հիշիր", "Ցածր լիկվիդության դեպքում տարբերությունը կարող է մեծ լինել", "narrow mountain road")],
  "Market՝|արագություն|գնի հաշվին",
  "Market order. ամենապարզ օրդերը և նրա թաքնված ռիսկը։",
  "Դու սովորաբար օգտագործո՞ւմ ես market order։",
  ["market order", "օրդեր", "թրեյդինգ", "crypto դաս"],
  ["Market orders execute immediately at the best available price."],
  Q("Ի՞նչ է երաշխավորում market order-ը", ["Կատարում", "Ճշգրիտ գին", "Շահույթ"]),
  ["market_order"], ["spread", "liquidity"]),
20: L("Limit Order", "concept", "Քո գինը|կամ|ոչինչ",
  [B("Limit order-ը կատարվում է միայն քո սահմանած գնով կամ ավելի լավ", "chess board closeup"),
   V(["Market", "Արագ, գինը՝ անհայտ"], ["Limit", "Գինը՝ հայտնի, կատարումը՝ ոչ"], "technology blue"),
   B("Եթե գինը չհասնի քո մակարդակին, օրդերը կմնա չկատարված", "hourglass sand")],
  "Limit՝|գին|ժամանակի հաշվին",
  "Limit order. ինչպես վերահսկել գինը և ինչ ես դրա դիմաց վճարում։",
  "Ո՞րն ես նախընտրում՝ market, թե limit։",
  ["limit order", "օրդեր", "թրեյդինգ", "crypto դաս"],
  ["Limit orders execute only at the set price or better and may not fill."],
  Q("Ո՞րն է limit order-ի ռիսկը", ["Կարող է չկատարվել", "Գինը անհայտ է", "Միշտ թանկ է"]),
  ["limit_order"], ["market_order"]),
21: L("Stop Order", "concept", "Օրդեր,|որը սպասում է|գնին",
  [B("Stop order-ը ակտիվանում է, երբ գինը հասնում է նշված մակարդակին", "hourglass sand"),
   B("Հաճախ այն օգտագործում են կորուստը սահմանափակելու համար", "padlock closeup"),
   C("Հիշիր", "Արագ շուկայում կատարման գինը կարող է տարբերվել", "ocean waves")],
  "Stop՝|նախօրոք|որոշված ելք",
  "Stop order. ինչպես է այն աշխատում և ինչու է կարևոր ռիսկի համար։",
  "Դու դնո՞ւմ ես stop order քո գործարքներում։",
  ["stop order", "stop loss", "օրդեր", "crypto դաս"],
  ["Stop orders trigger when price reaches a set level; fills can slip in fast markets."],
  Q("Ե՞րբ է ակտիվանում stop order-ը", ["Երբ գինը հասնում է մակարդակին", "Անմիջապես", "Օրվա վերջում"]),
  ["stop_order"], ["limit_order", "market_order"]),
22: L("Միջնորդավճարներ", "concept", "Փոքր տոկոսը|դառնում է|մեծ գումար",
  [B("Բորսաները գանձում են միջնորդավճար յուրաքանչյուր գործարքից", "money stack closeup"),
   K("Որտեղ են վճարները", ["Գնում և վաճառք", "Կանխիկացում", "Blockchain-ի ցանցի վճար"], "technology blue"),
   B("Հաճախակի գործարքների դեպքում վճարները կարող են ուտել շահույթի մեծ մասը", "hourglass sand")],
  "Հաշվիր|վճարները|նախօրոք",
  "Միջնորդավճարներ. որտեղ են դրանք թաքնված և ինչպես են ազդում արդյունքի վրա։",
  "Դու գիտե՞ս, թե որքան ես վճարում յուրաքանչյուր գործարքի համար։",
  ["trading fees", "միջնորդավճար", "crypto բորսա", "crypto դաս"],
  ["Fees apply to trades, withdrawals and network transfers."],
  Q("Ե՞րբ են վճարները ամենաշատ ազդում", ["Հաճախակի գործարքների դեպքում", "Երբեք", "Միայն մեկ գործարքում"]),
  ["fees"], ["exchange", "trading"]),
23: L("Հարկեր և կարգավորում", "concept", "Շահույթ.|իսկ|հարկե՞րը",
  [B("Crypto-ի հարկային կանոնները տարբեր երկրներում տարբեր են և փոխվում են", "city financial district"),
   K("Ինչ անել", ["Պահիր գործարքների գրառումները", "Ստուգիր պաշտոնական աղբյուրները", "Անհրաժեշտության դեպքում՝ մասնագետ"], "technology blue"),
   B("Կարգավորվող բորսաները պահանջում են անձի հաստատում", "bank vault door")],
  "Գրառումներ|այսօր,|հանգստություն վաղը",
  "Հարկեր և կարգավորում. ընդհանուր կանոններ, որոնք պետք է իմանա յուրաքանչյուր crypto օգտատեր։",
  "Դու պահո՞ւմ ես քո գործարքների գրառումները։",
  ["crypto հարկեր", "կարգավորում", "KYC", "crypto դաս"],
  ["Crypto tax rules differ by country and change over time."],
  Q("Ի՞նչ պահել միշտ", ["Գործարքների գրառումները", "Seed phrase-ը հեռախոսի նոթերում", "Ոչինչ"]),
  ["taxes"], ["exchange"]),
24: L("Ամփոփում + տնային առաջադրանք", "explain", "Մոդուլ 2.|ամբողջը|մեկ րոպեում",
  [B("Wallet-ը և seed phrase-ը քո գումարի բանալիներն են", "padlock closeup"),
   B("Scam-երը միշտ խոստանում են արագ և «ապահով» շահույթ", "dark storm clouds"),
   B("Բորսայում հիմնականը trading pair-ն է, օրդերները և վճարները", "technology network connection"),
   C("Տնային առաջադրանք", "Միացրու 2FA-ն և պահիր seed phrase-ը թղթի վրա, անվտանգ տեղում", "notebook handwriting pen")],
  "Մոդուլ 2|ավարտված է",
  "Մոդուլ 2-ի ամփոփում և տնային առաջադրանք։ Հաջորդը՝ ռիսկի հիմունքներ։",
  "Մոդուլ 2-ի ո՞ր դասն էր քեզ համար ամենաօգտակարը։",
  ["crypto անվտանգություն", "crypto դասընթաց", "crypto հայերեն", "trading դաս"],
  [],
  Q("Ի՞նչն է միշտ խոստանում scam-ը", ["Արագ, «ապահով» շահույթ", "Ռիսկի մասին զգուշացում", "Դասընթաց"]),
  [], ["wallet", "seed_phrase", "scam", "trading_pair", "fees"]),
}
